config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  get "/test", to: "pages#test", as: "test"

  # Privacy Notice
  resources :privacy_notices, only: [:index, :new, :create, :show]

  # Template routes
  get "/privacy_notices/:privacy_notice_id/template_one", to: "privacy_notices#template_one", as: "template_one", format: 'docx'
  get "/privacy_notices/:privacy_notice_id/template_two", to: "privacy_notices#template_two", as: "template_two", format: 'docx'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question, inverse_of: :answers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/privacy_notice.rb
class PrivacyNotice < ApplicationRecord
  #serialize :data_tag, Array
  serialize :reused_data, Array
  serialize :accessible_data, Array
  serialize :retained_data, Array

  before_save :convert_type_of_operation
  before_save :convert_organizer
  before_save :convert_organizer_under_contract
  before_save :convert_agency_name
  before_save :convert_collected_data
  before_save :convert_environment
  before_save :convert_shared_data
  before_save :convert_accessible_data
  before_save :convert_retained_data
  before_save :convert_reused_data
  before_save :convert_data_tag

  private

  def convert_type_of_operation
    if self.type_of_operation == "1"
      self.type_of_operation = "contest"
    elsif self.type_of_operation == "2"
      self.type_of_operation = "event"
    end
  end

  def convert_organizer
    if self.organizer == "3"
      self.organizer = "Ubisoft"
    elsif self.organizer == "4"
      self.organizer = "External agency"
    end
  end

  def convert_organizer_under_contract
    if self.organizer_under_contract == "5"
      self.organizer_under_contract = true
    elsif self.organizer_under_contract == "6"
      self.organizer_under_contract = false
    end
  end

  def convert_agency_name
    @answers = Answer.all
    if self.agency_name == "7"
      self.agency_name = "#{@answers.where(value: '7'.split).last.label}"
    elsif self.agency_name == "8"
      self.agency_name = "#{@answers.where(value: '7'.split).last.label}"
    elsif self.agency_name == "9"
      self.agency_name = nil
    end
  end

  def convert_collected_data
    @answers = Answer.all
    if self.collected_data == "10"
      self.collected_data = "Directly"
    elsif self.collected_data == "11"
      self.collected_data = "Indirectly"
    elsif self.collected_data == "12"
      self.collected_data = "Both"
    end
  end

  def convert_environment
    @answers = Answer.all
    if self.environment == "14"
      self.environment = "Ubisoft"
    elsif self.environment == "15"
      self.environment = "In-game"
    elsif self.environment == "16"
      self.environment = "Third party"
    elsif self.environment == "17"
      self.environment = "Social Network"
    end
  end

  def convert_shared_data
    if self.shared_data == "18"
      self.shared_data = true
    elsif self.shared_data == "19"
      self.shared_data = false
    end
  end

  def convert_reused_data
    if self.reused_data.include? "20"
      self.reused_data.delete "20"
      self.reused_data << "to create in-game content"
    end
    if self.reused_data.include? "21"
      self.reused_data.delete "21"
      self.reused_data << "to create promotional and marketing content"
    end
    if self.reused_data.include? "22"
      self.reused_data.delete "22"
      self.reused_data << "to send customer satisfaction survey"
    end
    if self.reused_data.include? "23"
      self.reused_data.delete "23"
      self.reused_data << "to conduct analytics about user experience"
    end
    if self.reused_data.include? "24"
      self.reused_data.delete "24"
      self.reused_data << "to send promotional offers"
    end
    if self.reused_data.include? "25"
      self.reused_data.delete "25"
      self.reused_data << "other"
    end
  end

  def convert_accessible_data
    self.accessible_data << "by recipients of promotional or marketing messages" if self.reused_data.include? "21"
  end

  def convert_retained_data
    self.retained_data << "to send you satisfaction survey" if self.reused_data.include? "22"
    self.retained_data << "manage analytics" if self.reused_data.include? "23"
    self.retained_data << "to send you promotional offers" if self.reused_data.include? "24"
  end

  def convert_data_tag
    if self.data_tag
      self.data_tag = self.data_tag.gsub('[', '').gsub(']', '').gsub('{"value":', '').gsub('}', '').gsub('"', '')
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy, inverse_of: :question
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @privacy_notice = PrivacyNotice.new
  end

  def test
    @privacy_notice = PrivacyNotice.new
    @questions = Question.all
    @answers = Answer.all
    gon.questions = @questions
    gon.answers = @answers
    render :test
  end
end

app/controllers/privacy_notices_controller.rb
class PrivacyNoticesController < ApplicationController
  before_action :set_privacy_notice, only: [:show]
  respond_to :docx

  def index
    render :index
  end

  def show
  end

  def new
    @privacy_notice = PrivacyNotice.new
    @questions = Question.all
    @answers = Answer.all
  end

  def create
    @privacy_notice = PrivacyNotice.new(privacy_notice_params)
    respond_to do |format|
      if @privacy_notice.save
        format.html { redirect_to @privacy_notice, notice: "Privacy Notice was successfully created." }
        format.json { render :show, status: :created, location: @privacy_notice }
      else
        format.html { redirect_to root_path, notice: "An error occured please contact IT" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  def template_one
    @privacy_notice = PrivacyNotice.find(params[:privacy_notice_id])
    respond_to do |format|
      if @privacy_notice.data_tag.empty? == false
        format.docx do
          render docx: 'template_one', filename: 'privacy_notice.docx'
        end
      else
        redirect_to root_path
      end
    end
  end

  def template_two
    @privacy_notice = PrivacyNotice.find(params[:privacy_notice_id])
    respond_to do |format|
      if @privacy_notice.data_tag.empty?
        format.docx do
          render docx: 'template_two', filename: 'privacy_notice.docx'
        end
      else
        redirect_to root_path
      end
    end
  end

  private

  def privacy_notice_params
    params.permit(:type_of_operation, :organizer, :collected_data, :environment, :shared_data, :agency_name, :data_tag, reused_data:[])
  end

  def set_privacy_notice
    @privacy_notice = PrivacyNotice.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def serialize_type_of_operation(param)
    param == "contest" ? "of the contest" : "of the event"
  end

  def serialize_organizer(param)
    param == "Ubisoft" ? "collect and process" : "to collect and process"
  end

  def serialize_collected_data(param)
    param == "Directly" ? "your personal data" : "the following personal data"
  end

  def serialize_data_tag(param)
    param.split(',')
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>TODO</title>
    <%= include_gon(:init => true) %>
    <%= Gon::Base.render_data({}) %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<section class="privacy-notice-container">
  <div class="left-home">
    <div class="container-from-left-home">
      <div class="welcome-message">Welcome !</div>
      <div class="generator-text">Here is the <strong>Privacy Notice Generator</strong> <span class="mr-robot">🤖</span>.
                                  <br>Ready ? Go to <strong>start</strong>.</div>
    </div>
  </div>
  <div class="right-home">
    <%= link_to new_privacy_notice_path, remote: true do %>
      <div class="start start-button">
        <span>START</span>
      </div>
    <% end %>
    <% if notice %>
      <p><%= notice %></p>
    <% else %>
    <% end %>
  </div>
</section>

app/views/pages/test.html.erb
<div class="form-group" style="position: absolute; top: 50%; right: 50%;">
  <%= form_for @privacy_notice do %>

  <%= select_tag @answers.where(question: 6).last.parameter.to_sym, options_for_select([ "7 derniers jours", "14 derniers jours", "30 derniers jours", "Depuis l'an dernier" ]), id: "created-at-input", class: "selectize", multiple: :true %>


    <%#= select_tag :privacy_notice_id, options_for_select(['numbers of views', 'numbers fo followers']),
                   { multiple: true, class: "selectize" } %>
  <% end %>
  <div class="button">
    Next
  </div>
</div>

app/views/privacy_notices/index.html.erb
<section class="privacy-notice-container-index">
  <%= link_to root_path do %>
    <div class="next-button purple-background">
        <span>Go back</span>
      </div>
  <% end %>
</section>

app/views/privacy_notices/new.html.erb
<%= render './privacy_notices/partials/form', privacy_notice: @privacy_notice %>

app/views/privacy_notices/new.js.erb
// $('.privacy-notice-container').html("<%= j render './privacy_notices/partials/form', privacy_notice: @privacy_notice %>")

// var end = $('.end');
// var previousQuestion = $('.previous-question');
// var currentQuestion = $('.current-qst');
// var radioButton = $("input[type=radio]");
// var checkboxButton = $("input[type=checkbox]");
// var textInput = $('input[name=data_tag]');
// var form = $('form');
// var currentButton = $('.current-btn');
// // var hintButton = $('.hint'),
// var count = 1;

// // HandleNextQuestion
// radioButton.each(function(){
//   var idVal = $(this).attr("id")

//   $(this).click(function(){
//     if($(this).prop("checked") ===  true) {

//       count += 1
//       let currentQst = currentQuestion.hasClass(`question-${count}`)
//       let currentBtn = currentButton.hasClass(`button-${count}`)

//       if(currentQst && idVal != "3" && idVal != "10" && idVal != "11" && idVal != "12") {
//         setTimeout(function(){
//           $(`form .question-${count}`).fadeIn(200, function(){$(this).removeClass('hidden')});
//         }, 300)
//         setTimeout(function(){
//           $(`form .question-${count - 1}`).fadeOut(200, function(){$(this).addClass('hidden')});
//         }, 300)
//       }
//       else if(currentQst && idVal == "3"){
//         count = 5
//         setTimeout(function(){
//           $(`form .question-${count}`).fadeIn(200, function(){$(this).removeClass('hidden')});
//         }, 300)
//         setTimeout(function(){
//           $(`form .question-${count - 3}`).fadeOut(200, function(){$(this).addClass('hidden')});
//         }, 300)
//       }
//       else if(currentQst && idVal == "10") {
//         count = 7
//         setTimeout(function(){
//           $(`form .question-${count}`).fadeIn(200, function(){$(this).removeClass('hidden')});
//         }, 300)
//         setTimeout(function(){
//           $(`form .question-${count - 2}`).fadeOut(200, function(){$(this).addClass('hidden')});
//         }, 300)
//       }
//       else if(currentQst && (idVal == "11" || idVal == "12")){
//         count = 6
//         setTimeout(function(){
//           $(`form .question-${count}`).fadeIn(200, function(){$(this).removeClass('hidden')});
//         }, 300)
//         setTimeout(function(){
//           $(`form .question-${count - 1}`).fadeOut(200, function(){$(this).addClass('hidden')});
//         }, 300)
//       }
//       $('.tagify').keyup(function(){
//         if(textInput.val().includes('value')){
//           setTimeout(function(){
//             $(`form .button-${count} .next-question`).fadeIn(200, function(){$(this).removeClass('hidden')});
//           }, 300)
//         }
//       });
//       $(`form .button-${count} .next-question`).click(function(){
//         count += 1
//         setTimeout(function(){
//           $(`form .question-${count}`).fadeIn(200, function(){$(this).removeClass('hidden')});
//         }, 300)
//         setTimeout(function(){
//           $(`form .question-${count - 1}`).fadeOut(200, function(){$(this).addClass('hidden')});
//         }, 300)
//       })
//     }
//   });
// });

//   // Previous question
//   // previous.click(function() {
//   //   count -= 1
//   //   let current = currentQuestion.hasClass(`question-${count}`)

//   //   if(current) {
//   //     setTimeout(function(){
//   //       $(`form .question-${count}`).fadeIn(200, function(){$(this).removeClass('hidden')});
//   //     }, 300)
//   //     setTimeout(function(){
//   //        $(`form .question-${count + 1}`).fadeOut(200, function(){$(this).removeClass('hidden')});
//   //     }, 300)
//   //   }
//   //   if(count <= 1){
//   //     setTimeout(function(){
//   //       previousQuestion.addClass('hidden');
//   //     }, 400)
//   //   }
//   // });

// // Enf of form
// checkboxButton.each(function(){
//   var idVal = $(this).attr("id")
//   $(this).click(function(){
//     if($(this).prop("checked") === true){
//       console.log(idVal)
//       setTimeout(function(){
//         end.removeClass('hidden');
//       }, 400)
//     }
//   })
// });

// // Prevent enter submit
// form.on('keypress', e => {
//   if (e.keyCode == 13) {
//     return false;
//   }
// });


// // $("input[type='radio']:checked").each(function() {
// //   var idVal = $(this).attr("id");
// //   alert($("label[for='"+idVal+"']").text());
// // });

// // function HandleModal(hintButton){
// //   hintButton.each(function(){
// //     $(this).click(function(){
// //       console.log($(this))
// //       var hintId = $(this).attr('id')
// //       $('#answer-modal-container').removeAttr('class').addClass(hintId)
// //       $('body').addClass('modal-active')
// //     })
// //   });
// //   $('#answer-modal-container').click(function(){
// //     $(this).addClass('out')
// //     $('body').removeClass('modal-active')
// //   });
// // };
// // HandleModal(hintButton)

// // Tagigy
// var tagifyInput = document.querySelector('input[name=data_tag]'),
//     tagify1 = new Tagify(tagifyInput, { whitelist : ['Number of hours spent on game', 'Participation in a beta of a game',
//                                                      'Participation in event', 'Posts on social networks', 'Number of followers',
//                                                      'Number of views on videos'] });

app/views/privacy_notices/partials/_form.html.erb
r<div class="left-form">
  <div class="container-from-left-form"></div>
</div>

<div class="right-form">
  <%= form_tag @privacy_notice do %>
    <% @questions.each_with_index do |question, index| %>
      <div class="current-qst question-<%= index + 1 %> <%= question.position == 1 ? '' : 'hidden' %>">
        <div class="question-title"><%= question.title %></div>
        <div class="labels-container">
          <% question.answers.each do |answer| %>
            <% if answer.answer_type == "radio" %>
              <div class="radio-input">
                <%= tag.input type: answer.answer_type, label: false, id: answer.order.to_s, value: answer.value,
                              name: answer.parameter %>
                <%= tag.label answer.label, for: answer.order.to_s %>
              </div>
            <% elsif answer.answer_type == "text" %>
              <div class="text-input">
                <%= tag.label answer.label, for: answer.order.to_s %>
                <%= tag.input type: answer.answer_type, label: false, id: answer.order.to_s, name: answer.parameter %>
              </div>
            <% elsif answer.answer_type == "checkbox" %>
              <div class="checkbox-input">
                <%= tag.input type: answer.answer_type, label: false, id: answer.order.to_s, value: answer.value,
                              name: "#{answer.parameter}[]" %>
                <%= tag.label answer.label, for: answer.order.to_s %>
              </div>
            <% end %>
          <% end %>
          <div class="form-buttons current-btn button-<%= index + 1 %>">
            <div class="previous-question hidden">Back</div>
            <div class="next-question next-button purple-background hidden">Next</div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="form-buttons">
      <%= submit_tag "Create", class: "end next-button purple-background hidden" %>
    </div>
  <% end %>
</div>

app/views/privacy_notices/partials/_radio_form.html.erb
<%# if answer.hint %>
<!--   <div id="answer-modal-container">
    <div class="modal-background">
      <div class="modal">
        <h2>I'm a modal</h2>
        <%= answer.value %>
      </div>
    </div>
  </div>
  <div class="radio-input">
    <div class="hint" id="one">?</div>
    <%= tag.input type: answer.answer_type, label: false, id: answer.order.to_s, value: answer.value,
                  name: answer.parameter %>
    <%= tag.label answer.label, for: answer.order.to_s %>
  </div> -->
<%# else %>
  <div class="radio-input">
    <%= tag.input type: answer.answer_type, label: false, id: answer.order.to_s, value: answer.value,
                  name: answer.parameter %>
    <%= tag.label answer.label, for: answer.order.to_s %>
  </div>
<%# end %>

app/views/privacy_notices/show.html.erb
<div class="container" style="padding: 100px; text-align: center">
  <%= notice %><br><br>
  <%= @privacy_notice.attributes %><br><br><br>
  <strong>Type of operation : </strong>  <%= @privacy_notice.type_of_operation %><br>
  <strong>Organizer : </strong>  <%= @privacy_notice.organizer %><br>
  <strong>Collected data : </strong>  <%= @privacy_notice.collected_data %><br>
  <strong>Environment : </strong>  <%= @privacy_notice.environment %><br>
  <strong>Shared data : </strong>  <%= @privacy_notice.shared_data %><br>
  <strong>Reused data : </strong>  <%= @privacy_notice.reused_data %><br>
  <strong>Organizer under contract : </strong>  <%= @privacy_notice.organizer_under_contract %><br>
  <strong>Agency name : </strong>  <%= @privacy_notice.agency_name %><br>
  <strong>Data tag : </strong>  <%= @privacy_notice.data_tag %><br><br>

  <% if @privacy_notice.data_tag.empty? %>
    <%= link_to "download", template_two_path(@privacy_notice) %>
  <% else %>
    <%= link_to "download", template_one_path(@privacy_notice) %>
  <% end %>
</div>

app/views/privacy_notices/template_one.docx.erb
<div class="container">
  <div class="first-paraph">
    As part <%= serialize_type_of_operation(@privacy_notice.type_of_operation) %>, Ubisoft Entertainment (107 avenue Henri Fréville, BP 10704, 35207 Rennes Cedex 2, France) <% if @privacy_notice.organizer_under_contract %> outsourced <%= @privacy_notice.agency_name %><% end %> <%= serialize_organizer(@privacy_notice.organizer) %> <%= serialize_collected_data(@privacy_notice.collected_data) %> <% if @privacy_notice.shared_data %>in order to allow you to participate in the contest,  contact winners to give the awards and shared the content you will publish<% else %>in order to allow you to participate in the contest and contact winners to give the awards<% end %> :
    <% serialize_data_tag(@privacy_notice.data_tag).each_with_index do |param, index| %>
      <% if param == serialize_data_tag(@privacy_notice.data_tag).last %>
        <%= "(#{'i'*(index + 1)}) #{param}." %>
      <% else %>
        <%= "(#{'i'*(index + 1)}) #{param}, " %>
      <% end %>
    <% end %> These data will be deleted after the contest.
  </div>

  <% if !@privacy_notice.reused_data.empty? %>
    <div class="second-paraph">
      Your personal data may be used
      <% @privacy_notice.reused_data.each do |param| %>
        <% if @privacy_notice.reused_data.length == 1 %>
          <%= param %>.
        <% else %>
          <% if param == @privacy_notice.reused_data.last %>
            <%= "and #{param}." %>
          <% else %>
            <% if param == @privacy_notice.reused_data[-2] %>
              <%= param %>
            <% else %>
              <%= "#{param}, " %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      These uses are based on the execution of this contract with Ubisoft.
    </div>

    <div class="third-paraph">
      <% if !@privacy_notice.accessible_data.empty? %>
        Your personal data will be accessible by Ubisoft, its affiliates and subcontractor, the users of the media on which you will publish your content as part of the contest and <%= @privacy_notice.accessible_data.last %>.
      <% else %>
        Your personal data will be accessible by Ubisoft, its affiliates and subcontractor and the users of the media on which you will publish your content as part of the contest.
      <% end %>
      <% if !@privacy_notice.retained_data.empty? %>
        Your personal data will be retained until you delete the content that you shared and as long as you agree that Ubisoft
          <% @privacy_notice.retained_data.each do |param| %>
            <% if @privacy_notice.retained_data.length == 1 %>
              <%= param %>.
            <% else %>
              <% if param == @privacy_notice.retained_data.last %>
                <%= "or #{param}." %>
              <% else %>
                <% if param == @privacy_notice.retained_data[-2] %>
                  <%= param %>
                <% else %>
                  <%= "#{param}, " %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>.
      <% end %>
    </div>
  <% end %>

  <div class="fourth-paraph">
    Your informations may be transfered to third countries to the European Union,  either because they carry out   an adequate level of protection recognized by the European Commission or because the level of protection is carried out by the signature contractual clauses validated by the European Commission.
  </div>

  <div class="fifth-paraph">
    You can withdraw you consent at any time and claim your right to access, to modify, to oppose, to delete, and your portability right for every personal data by contacting the Data Protection Officer. If the use of your personal data is prejudicial, made a complaint to the competent autority of your country.
  </div>
</div>

app/views/privacy_notices/template_one.html.erb
<div class="container">
  <div class="first-paraph">
    As part <%= serialize_type_of_operation(@privacy_notice.type_of_operation) %>, Ubisoft Entertainment (107 avenue Henri Fréville, BP 10704, 35207 Rennes Cedex 2, France) <% if @privacy_notice.organizer_under_contract %> outsourced <%= @privacy_notice.agency_name %><% end %> <%= serialize_organizer(@privacy_notice.organizer) %> <%= serialize_collected_data(@privacy_notice.collected_data) %> <% if @privacy_notice.shared_data %>in order to allow you to participate in the contest,  contact winners to give the awards and shared the content you will publish<% else %>in order to allow you to participate in the contest and contact winners to give the awards<% end %> :
    <% serialize_data_tag(@privacy_notice.data_tag).each_with_index do |param, index| %>
      <% if param == serialize_data_tag(@privacy_notice.data_tag).last %>
        <%= "(#{'i'*(index + 1)}) #{param}." %>
      <% else %>
        <%= "(#{'i'*(index + 1)}) #{param}, " %>
      <% end %>
    <% end %> These data will be deleted after the contest.
  </div>

  <% if !@privacy_notice.reused_data.empty? %>
    <div class="second-paraph">
      Your personal data may be used
      <% @privacy_notice.reused_data.each do |param| %>
        <% if @privacy_notice.reused_data.length == 1 %>
          <%= param %>.
        <% else %>
          <% if param == @privacy_notice.reused_data.last %>
            <%= "and #{param}." %>
          <% else %>
            <% if param == @privacy_notice.reused_data[-2] %>
              <%= param %>
            <% else %>
              <%= "#{param}, " %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      These uses are based on the execution of this contract with Ubisoft.
    </div>

    <div class="third-paraph">
      <% if !@privacy_notice.accessible_data.empty? %>
        Your personal data will be accessible by Ubisoft, its affiliates and subcontractor, the users of the media on which you will publish your content as part of the contest and <%= @privacy_notice.accessible_data.last %>.
      <% else %>
        Your personal data will be accessible by Ubisoft, its affiliates and subcontractor and the users of the media on which you will publish your content as part of the contest.
      <% end %>
      <% if !@privacy_notice.retained_data.empty? %>
        Your personal data will be retained until you delete the content that you shared and as long as you agree that Ubisoft
          <% @privacy_notice.retained_data.each do |param| %>
            <% if @privacy_notice.retained_data.length == 1 %>
              <%= param %>.
            <% else %>
              <% if param == @privacy_notice.retained_data.last %>
                <%= "or #{param}." %>
              <% else %>
                <% if param == @privacy_notice.retained_data[-2] %>
                  <%= param %>
                <% else %>
                  <%= "#{param}, " %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>.
      <% end %>
    </div>
  <% end %>

  <div class="fourth-paraph">
    Your informations may be transfered to third countries to the European Union,  either because they carry out   an adequate level of protection recognized by the European Commission or because the level of protection is carried out by the signature contractual clauses validated by the European Commission.
  </div>

  <div class="fifth-paraph">
    You can withdraw you consent at any time and claim your right to access, to modify, to oppose, to delete, and your portability right for every personal data by contacting the Data Protection Officer. If the use of your personal data is prejudicial, made a complaint to the competent autority of your country.
  </div>
</div>

app/views/privacy_notices/template_two.docx.erb
<div class="container">
  <div class="first-paraph">
    As part <%= serialize_type_of_operation(@privacy_notice.type_of_operation) %>, Ubisoft Entertainment (107 avenue Henri Fréville, BP 10704, 35207 Rennes Cedex 2, France) <% if @privacy_notice.organizer_under_contract %> outsourced <%= @privacy_notice.agency_name %><% end %> <%= serialize_organizer(@privacy_notice.organizer) %> <%= serialize_collected_data(@privacy_notice.collected_data) %> <% if @privacy_notice.shared_data %>in order to allow you to participate in the contest, contact winners to give the awards and shared the content you will publish<% else %>in order to allow you to participate in the contest and contact winners to give the awards<% end %>.
  </div>

  <% if !@privacy_notice.reused_data.empty? %>
    <div class="second-paraph">
      Your personal data may be used
      <% @privacy_notice.reused_data.each do |param| %>
        <% if @privacy_notice.reused_data.length == 1 %>
          <%= param %>.
        <% else %>
          <% if param == @privacy_notice.reused_data.last %>
            <%= "and #{param}." %>
          <% else %>
            <% if param == @privacy_notice.reused_data[-2] %>
              <%= param %>
            <% else %>
              <%= "#{param}, " %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
      These uses are based on the execution of this contract with Ubisoft.
    </div>

    <div class="third-paraph">
      <% if !@privacy_notice.accessible_data.empty? %>
        Your personal data will be accessible by Ubisoft, its affiliates and subcontractor, the users of the media on which you will publish your content as part of the contest and <%= @privacy_notice.accessible_data.last %>.
      <% else %>
        Your personal data will be accessible by Ubisoft, its affiliates and subcontractor and the users of the media on which you will publish your content as part of the contest.
      <% end %>
      <% if !@privacy_notice.retained_data.empty? %>
        Your personal data will be retained until you delete the content that you shared and as long as you agree that Ubisoft
          <% @privacy_notice.retained_data.each do |param| %>
            <% if @privacy_notice.retained_data.length == 1 %>
              <%= param %>.
            <% else %>
              <% if param == @privacy_notice.retained_data.last %>
                <%= "or #{param}." %>
              <% else %>
                <% if param == @privacy_notice.retained_data[-2] %>
                  <%= param %>
                <% else %>
                  <%= "#{param}, " %>
                <% end %>
              <% end %>
            <% end %>
          <% end %>.
      <% end %>
    </div>
  <% end %>

  <div class="fourth-paraph">
    Your informations may be transfered to third countries to the European Union,  either because they carry out   an adequate level of protection recognized by the European Commission or because the level of protection is carried out by the signature contractual clauses validated by the European Commission.
  </div>

  <div class="fifth-paraph">
    You can withdraw you consent at any time and claim your right to access, to modify, to oppose, to delete, and your portability right for every personal data by contacting the Data Protection Officer. If the use of your personal data is prejudicial, made a complaint to the competent autority of your country.
  </div>
</div>